language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t valyaevilya/service-image-colorization:test .

script:
  - docker run -d -p 8080:8080 valyaevilya/service-image-colorization:test /bin/sh -c 'make test'
